"""TurnEvolutionProposal — structured output from TurnEvolutionCurator.

schemaId: awp.rp.turn-evolution-proposal.v1

Generated by the curator after Writer text is accepted by QualityGate.
Contains:
  - state_update_proposal: candidate CardStatePatch operations
  - memory_candidates: active and RAG memory suggestions
  - event_summary: what happened this turn
  - relationship_summary: relationship changes this turn

The proposal is validated and committed through CardStateCommitRuntime.
No agent may write state or memory directly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

SCHEMA_ID = "awp.rp.turn-evolution-proposal.v1"
SCHEMA_VERSION = 1


@dataclass
class StateUpdateProposalV2:
    """Proposed state changes with revision tracking.

    Must pass through Patch Validator before CardStateCommitRuntime.
    """
    expected_revision: int = 0
    operations: list[dict[str, Any]] = field(default_factory=list)
    reasoning_summary: str = ""
    evidence: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        return len(self.operations) == 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "expected_revision": self.expected_revision,
            "operations": list(self.operations),
            "reasoning_summary": self.reasoning_summary,
            "evidence": list(self.evidence),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> StateUpdateProposalV2:
        return cls(
            expected_revision=data.get("expected_revision", 0),
            operations=list(data.get("operations", [])),
            reasoning_summary=data.get("reasoning_summary", ""),
            evidence=list(data.get("evidence", [])),
        )


@dataclass
class MemoryCandidate:
    """A single memory candidate (active or RAG)."""
    layer: str = "active"  # "active" or "rag"
    kind: str = ""  # ActiveMemoryKind value for active, "turn_record" for RAG
    content: str = ""
    importance: float = 0.5
    entity_refs: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    source_hash: str = ""
    reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "layer": self.layer,
            "kind": self.kind,
            "content": self.content,
            "importance": self.importance,
            "entity_refs": list(self.entity_refs),
            "tags": list(self.tags),
            "source_hash": self.source_hash,
            "reason": self.reason,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MemoryCandidate:
        return cls(
            layer=data.get("layer", "active"),
            kind=data.get("kind", ""),
            content=data.get("content", ""),
            importance=data.get("importance", 0.5),
            entity_refs=list(data.get("entity_refs", [])),
            tags=list(data.get("tags", [])),
            source_hash=data.get("source_hash", ""),
            reason=data.get("reason", ""),
        )


@dataclass
class TurnEvolutionProposal:
    """Complete structured output from TurnEvolutionCurator.

    Contains state proposals, memory candidates, event summaries,
    and relationship summaries. All are proposals — nothing is committed
    until validated.
    """
    schema_id: str = SCHEMA_ID
    schema_version: int = SCHEMA_VERSION

    # Identity
    proposal_id: str = ""
    turn_id: str = ""
    session_id: str = ""

    # State proposals
    state_update_proposal: StateUpdateProposalV2 = field(
        default_factory=StateUpdateProposalV2
    )

    # Memory candidates
    memory_candidates_active: list[MemoryCandidate] = field(default_factory=list)
    memory_candidates_rag: list[MemoryCandidate] = field(default_factory=list)

    # Event and relationship summaries (safe for UI projection)
    event_summary: list[dict[str, Any]] = field(default_factory=list)
    relationship_summary: list[dict[str, Any]] = field(default_factory=list)

    # Diagnostics
    curator_confidence: float = 0.0
    curator_reasoning: str = ""
    is_no_state_change: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_id": self.schema_id,
            "schema_version": self.schema_version,
            "proposal_id": self.proposal_id,
            "turn_id": self.turn_id,
            "session_id": self.session_id,
            "state_update_proposal": self.state_update_proposal.to_dict(),
            "memory_candidates_active": [
                c.to_dict() for c in self.memory_candidates_active
            ],
            "memory_candidates_rag": [
                c.to_dict() for c in self.memory_candidates_rag
            ],
            "event_summary": list(self.event_summary),
            "relationship_summary": list(self.relationship_summary),
            "curator_confidence": self.curator_confidence,
            "curator_reasoning": self.curator_reasoning,
            "is_no_state_change": self.is_no_state_change,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TurnEvolutionProposal:
        return cls(
            schema_id=data.get("schema_id", SCHEMA_ID),
            schema_version=data.get("schema_version", SCHEMA_VERSION),
            proposal_id=data.get("proposal_id", ""),
            turn_id=data.get("turn_id", ""),
            session_id=data.get("session_id", ""),
            state_update_proposal=StateUpdateProposalV2.from_dict(
                data.get("state_update_proposal", {})
            ),
            memory_candidates_active=[
                MemoryCandidate.from_dict(c)
                for c in data.get("memory_candidates_active", [])
            ],
            memory_candidates_rag=[
                MemoryCandidate.from_dict(c)
                for c in data.get("memory_candidates_rag", [])
            ],
            event_summary=list(data.get("event_summary", [])),
            relationship_summary=list(data.get("relationship_summary", [])),
            curator_confidence=data.get("curator_confidence", 0.0),
            curator_reasoning=data.get("curator_reasoning", ""),
            is_no_state_change=data.get("is_no_state_change", False),
        )
